name: Compilar APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Generar Wrapper y Compilar APK
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace 2>&1 | tee build.log

      - name: Mostrar log en el resumen si falla
        if: failure()
        run: |
          echo "## Log de compilación" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          tail -n 150 build.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Subir APK generado
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Lupa-APK
          path: app/build/outputs/apk/debug/*.apk
