name: Compilar APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Generar Wrapper y Compilar APK
        run: |
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace 2>&1 | tee build.log

      - name: Subir APK generado
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Lupa-APK
          path: app/build/outputs/apk/debug/*.apk

      - name: Subir registro si falla
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Log-Error-Compilacion
          path: |
            build.log
            app/build/reports/
